import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"

const noticeUrl = new URL("../THIRD_PARTY_LICENSES.md", import.meta.url)

test("packaged dashboard carries the licenses for its bundled code", () => {
  const notice = readFileSync(noticeUrl, "utf8")
  const expectedLicenses = new Map([
    ["@base-ui/react", "MIT"],
    ["@base-ui/utils", "MIT"],
    ["@floating-ui/utils", "MIT"],
    ["@microsoft/fetch-event-source", "MIT"],
    ["@tanstack/history", "MIT"],
    ["@tanstack/query-core", "MIT"],
    ["@tanstack/react-query", "MIT"],
    ["@tanstack/react-router", "MIT"],
    ["@tanstack/react-store", "MIT"],
    ["@tanstack/router-core", "MIT"],
    ["@tanstack/store", "MIT"],
    ["class-variance-authority", "Apache-2.0"],
    ["clsx", "MIT"],
    ["lucide-react", "ISC"],
    ["react", "MIT"],
    ["react-dom", "MIT"],
    ["reselect", "MIT"],
    ["scheduler", "MIT"],
    ["tailwind-merge", "MIT"],
    ["tailwindcss", "MIT"],
    ["tw-animate-css", "MIT"],
    ["use-sync-external-store", "MIT"],
  ])
  const emittedLicenses = new Map(
    [...notice.matchAll(/^## (.+) - \S+ \(([^)]+)\)$/gm)].map((match) => [match[1], match[2]]),
  )
  const reviewedLicenses = new Set(["Apache-2.0", "ISC", "MIT"])

  assert.match(notice, /^<!-- Generated by Vite/m)
  assert.deepEqual([...emittedLicenses.keys()].sort(), [...expectedLicenses.keys()].sort())
  for (const [packageName, expectedLicense] of expectedLicenses) {
    assert.equal(emittedLicenses.get(packageName), expectedLicense)
  }
  for (const license of emittedLicenses.values()) {
    assert.ok(
      reviewedLicenses.has(license),
      `unexpected bundled license requiring review: ${license}`,
    )
  }
  assert.match(notice, /^## shadcn\/ui registry source \(MIT\)$/m)
  assert.match(notice, /Copyright \(c\) 2013-present Cole Bemis/)
  assert.doesNotMatch(notice, /Geist/)
})
