"""Private, standalone visual evidence owner copied into the browser image.

All DOM objects live in a CDP isolated world. Only bounded JSON evidence crosses
to the host. The event guard is installed before page scripts and checks the
retained target again at native input delivery; it never synthesizes a DOM click.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import math
import secrets
import time
from dataclasses import dataclass, field
from typing import Any
from urllib.parse import urlsplit


class VisualGuestFailure(Exception):
    def __init__(self, code: str) -> None:
        super().__init__(code)
        self.code = code


_WORLD = "cayu-browser-visual-v1"
VISUAL_FAILURE_CODES = frozenset(
    {
        "visual_mode_disabled",
        "visual_publication_denied",
        "unstable_visual_observation",
        "visual_evidence_expired",
        "unknown_visual_target",
        "visual_viewport_mismatch",
        "visual_page_mismatch",
        "visual_cross_frame_refused",
        "visual_hit_test_mismatch",
        "visual_target_not_actionable",
        "visual_point_outside_viewport",
        "unsupported_visual_surface",
    }
)


def visual_policy_from_json(raw: Any) -> dict[str, Any] | None:
    if raw is None:
        return None
    bounds = {
        "max_width": (1, 4096),
        "max_height": (1, 4096),
        "max_pixels": (1, 8_000_000),
        "max_bytes": (1, 8 * 1024 * 1024),
        "max_targets": (1, 256),
        "max_label_bytes": (0, 512),
        "max_hit_tests": (1, 1024),
        "max_frame_depth": (0, 16),
        "max_processing_ms": (1, 30_000),
        "max_captures": (1, 256),
        "evidence_lifetime_ms": (1, 120_000),
    }
    flags = {
        "publish_to_model",
        "allow_coordinate_fallback",
        "allow_authenticated_pages",
        "capture_during_sensitive_takeover",
    }
    if type(raw) is not dict or set(raw) != set(bounds) | flags | {
        "artifact_store_id",
        "allowed_origins",
        "allowed_profile_contexts",
        "retention",
    }:
        raise VisualGuestFailure("visual_publication_denied")
    for name, (low, high) in bounds.items():
        if type(raw[name]) is not int or not low <= raw[name] <= high:
            raise VisualGuestFailure("visual_publication_denied")
    if (
        any(type(raw[name]) is not bool for name in flags)
        or raw["capture_during_sensitive_takeover"] is not False
        or raw["allow_authenticated_pages"] is not False
        or raw["allowed_profile_contexts"] != ["fresh_temporary"]
    ):
        raise VisualGuestFailure("visual_publication_denied")
    if (
        raw["retention"] != "application_managed"
        or type(raw["artifact_store_id"]) is not str
        or not 0 < len(raw["artifact_store_id"]) <= 256
    ):
        raise VisualGuestFailure("visual_publication_denied")
    origins = raw["allowed_origins"]
    if type(origins) is not list or not 0 < len(origins) <= 64:
        raise VisualGuestFailure("visual_publication_denied")
    for origin in origins:
        if type(origin) is not str or len(origin) > 2048:
            raise VisualGuestFailure("visual_publication_denied")
        parsed = urlsplit(origin)
        if (
            parsed.scheme != "https"
            or not parsed.hostname
            or parsed.username
            or parsed.password
            or parsed.port not in {None, 443}
            or parsed.path
            or parsed.query
            or parsed.fragment
        ):
            raise VisualGuestFailure("visual_publication_denied")
    if (
        raw["max_width"] * raw["max_height"] > raw["max_pixels"]
        or raw["max_targets"] > raw["max_hit_tests"]
    ):
        raise VisualGuestFailure("visual_publication_denied")
    return dict(raw)


# The key is generated by the guest, not by the page or model. The isolated world
# has its own globals and intrinsic prototypes. No page-supplied script is run.
_INSTALL = r"""(() => {
 const key = __KEY__;
 if (globalThis[key]) return;
 const own = {document, targets: new Map(), arm: null, revision: null, dirty:false};
 own.observer = new MutationObserver(() => { own.dirty=true; });
 own.observer.observe(document,{subtree:true,childList:true,attributes:true,characterData:true});
 const viewport = () => [innerWidth, innerHeight, devicePixelRatio, scrollX, scrollY];
 const rect = node => {
   const r = node.getBoundingClientRect();
   return [r.x, r.y, r.width, r.height];
 };
 const same = (a,b) => a.length === b.length && a.every((v,i) => v === b[i]);
 const hit = (x,y) => {
   let node = document.elementFromPoint(x,y);
   for (let depth=0; node && node.shadowRoot && depth<16; depth++) {
     const inner = node.shadowRoot.elementFromPoint(x,y);
     if (!inner || inner === node) break;
     node = inner;
   }
   return node;
 };
 const refused = node => !node || node.ownerDocument !== document ||
   node.localName === 'iframe' || node.localName === 'frame' ||
   node.localName === 'object' || node.localName === 'embed';
 // These HTML elements cannot host author shadow roots. A retargeted host is
 // not proof of the actual receiving element: closed roots hide that element
 // from both elementFromPoint and the window's composedPath. Refuse opaque
 // surfaces rather than infer that they contain no denied controls.
 const provenSurface = node => node && (
   (node.namespaceURI === 'http://www.w3.org/2000/svg' && node.localName !== 'use') ||
   (node.namespaceURI === 'http://www.w3.org/1999/xhtml' &&
    ['canvas','img','button','a','input'].includes(node.localName)));
 const actionable = node => node.isConnected && !node.closest('[inert]') &&
   !node.matches(':disabled') && node.getAttribute('aria-disabled') !== 'true' &&
   !(node.localName === 'input' && ['password','file','hidden'].includes(node.type)) &&
   getComputedStyle(node).visibility === 'visible' &&
   getComputedStyle(node).pointerEvents !== 'none';
 const validate = (target,x,y) => {
   if (!same(viewport(),own.viewport)) return 'visual_viewport_mismatch';
   if (!target || !target.node.isConnected || target.node.ownerDocument !== document)
     return 'visual_evidence_expired';
   if (!same(rect(target.node),target.rect)) return 'visual_hit_test_mismatch';
   const current = hit(x,y);
   if (refused(current)) return 'visual_cross_frame_refused';
   if (!provenSurface(current)) return 'unsupported_visual_surface';
   if (current !== target.hit || !target.node.contains(current))
     return 'visual_hit_test_mismatch';
   if (!actionable(target.node) || !actionable(current)) return 'visual_target_not_actionable';
   return null;
 };
 own.viewportNow = viewport;
 own.rect = rect;
 own.hit = hit;
 own.refused = refused;
 own.provenSurface = provenSurface;
 own.actionable = actionable;
 own.validate = validate;
 for (const type of ['pointerdown','mousedown','pointerup','mouseup','click','dblclick','auxclick']) {
   addEventListener(type, event => {
     const arm = own.arm;
     if (!arm) return;
     // takeRecords covers mutations not yet delivered to the observer. Once
     // pointerdown is admitted, its own handlers may legitimately mutate DOM.
     // A refused first event stays refused for the remainder of this input.
     const stale = !arm.dispatched && (own.dirty || own.observer.takeRecords().length);
     const failure = arm.failure || (stale ? 'visual_evidence_expired' :
       validate(arm.target,event.clientX,event.clientY));
     if (failure || event.clientX !== arm.x || event.clientY !== arm.y ||
         event.composedPath()[0] !== arm.target.hit || !event.isTrusted) {
       arm.failure = failure || 'visual_hit_test_mismatch';
       event.preventDefault(); event.stopImmediatePropagation(); return;
     }
     arm.dispatched = true;
     if (type === 'click') {
       arm.clicked = true;
       globalThis[key+'Delivery']('click');
     }
   }, {capture:true, passive:false});
 }
 Object.defineProperty(globalThis,key,{value:own});
})()"""

_COLLECT = r"""(() => {
 const own = globalThis[__KEY__], options = __OPTIONS__, refs = __REFS__;
 if (!own || own.document !== document) return {error:'visual_evidence_expired'};
 const view = own.viewportNow();
 if (!view.every(Number.isFinite) || view[0] <= 0 || view[1] <= 0 ||
     view[0] > options.max_width || view[1] > options.max_height ||
     view[0]*view[1]*view[2]*view[2] > options.max_pixels ||
     view[2] <= 0 || view[2] > 4 || view[3] < 0 || view[4] < 0)
   return {error:'visual_viewport_mismatch'};
 own.targets.clear(); own.arm=null; own.viewport=view;
 own.observer.disconnect();
 own.observer.observe(document,{subtree:true,childList:true,attributes:true,characterData:true});
 own.dirty=false;
 const output=[], truncation=new Set(), unsupported=new Set();
 const label = node => {
   const raw = node.getAttribute('aria-label') || node.getAttribute('alt') ||
     node.getAttribute('title') || '';
   let text='', bytes=0;
   for (const c of raw) {
     const n = new TextEncoder().encode(c).length;
     if (bytes+n > options.max_label_bytes) { truncation.add('labels'); break; }
     text += c; bytes += n;
   }
   return text;
 };
 const stack=[document.documentElement]; let inspected=0, tests=0;
 while (stack.length) {
   const node=stack.pop(); if (!node) continue;
   if (++inspected > options.max_dom_nodes) return {error:'unsupported_visual_surface'};
   for (let child=node.lastElementChild; child; child=child.previousElementSibling) {
     if (stack.length+inspected >= options.max_dom_nodes) return {error:'unsupported_visual_surface'};
     stack.push(child);
   }
   if (node.shadowRoot) {
     own.observer.observe(node.shadowRoot,{subtree:true,childList:true,attributes:true,characterData:true});
     stack.push(node.shadowRoot);
   }
   if (!(node instanceof Element)) continue;
   if (own.refused(node)) {unsupported.add('embedded_surface'); continue;}
   const style=getComputedStyle(node);
   if (!['canvas','img','svg','button','a','input'].includes(node.localName) &&
       !node.hasAttribute('role') && !node.hasAttribute('onclick') &&
       !node.hasAttribute('tabindex') && style.cursor !== 'pointer') continue;
   const r=own.rect(node), [x,y,w,h]=r;
   if (!r.every(Number.isFinite) || w<=0 || h<=0 || x<0 || y<0 ||
       x+w>view[0] || y+h>view[1] || style.visibility!=='visible') continue;
   if (tests >= options.max_hit_tests) {truncation.add('hit_tests'); break;}
   tests++;
   const cx=Math.floor(x+w/2),cy=Math.floor(y+h/2),current=own.hit(cx,cy);
   const occluded=!current || !node.contains(current) || own.refused(current);
   const supported=own.provenSurface(current);
   if (!supported) unsupported.add('opaque_surface');
   if (output.length >= refs.length) {truncation.add('targets'); break;}
   const ref=refs[output.length];
   own.targets.set(ref,{node,hit:current,rect:r,x:cx,y:cy});
   output.push({ref,geometry:{x:x/view[0],y:y/view[1],width:w/view[0],height:h/view[1]},
     visible:true,occluded,actionable:!occluded && supported && own.actionable(node) && own.actionable(current),
     label:label(node),role:Array.from(node.getAttribute('role')||'').slice(0,128).join(''),frame_depth:0});
 }
 return {viewport:view,targets:output,truncation_reasons:[...truncation],
   unsupported_reasons:[...unsupported]};
})()"""

_CHECK = r"""(() => {
 const own=globalThis[__KEY__]; if (!own || own.document !== document) return false;
 if (own.dirty || own.observer.takeRecords().length) return false;
 if (JSON.stringify(own.viewportNow()) !== JSON.stringify(own.viewport)) return false;
 for (const target of own.targets.values()) {
   if (!target.node.isConnected || JSON.stringify(own.rect(target.node)) !== JSON.stringify(target.rect) ||
       own.hit(target.x,target.y) !== target.hit) return false;
 }
 return true;
})()"""

_ARM = r"""(() => {
 const own=globalThis[__KEY__], request=__REQUEST__;
 if (!own || own.document !== document) return {error:'visual_evidence_expired'};
 if (own.dirty || own.observer.takeRecords().length) return {error:'visual_evidence_expired'};
 let target,x,y;
 if (request.visual_ref) {
   target=own.targets.get(request.visual_ref);
   if (!target) return {error:'unknown_visual_target'};
   x=target.x; y=target.y;
 } else {
   x=Math.floor(request.x*own.viewport[0]); y=Math.floor(request.y*own.viewport[1]);
   // Only capture-time samples prove what the screenshot showed at this
   // precise point. Never manufacture authority from a fresh hit test or
   // silently snap an unsampled point to a nearby retained target.
   target=Array.from(own.targets.values()).find(item => item.x === x && item.y === y);
   if (!target) return {error:'unsupported_visual_surface'};
 }
 const error=own.validate(target,x,y); if (error) return {error};
 own.arm={target,x,y,dispatched:false,clicked:false,failure:null};
 return {x,y};
})()"""


def _script(source: str, key: str, **values: Any) -> str:
    source = source.replace("__KEY__", json.dumps(key))
    for name, value in values.items():
        source = source.replace(f"__{name.upper()}__", json.dumps(value, separators=(",", ":")))
    return source


@dataclass
class VisualPageOwner:
    cdp: Any
    worker_instance: str
    key: str = field(default_factory=lambda: "cayuVisual" + secrets.token_hex(24))
    context_id: int | None = None
    document_identity: tuple[str, str, str] | None = None
    evidence: dict[str, Any] | None = None
    expires_at: float = 0
    clicked: bool = False
    action_task: asyncio.Task[None] | None = None
    disarm_task: asyncio.Task[None] | None = None

    async def install(self) -> None:
        await self.cdp.send(
            "Runtime.addBinding",
            {
                "name": self.key + "Delivery",
                "executionContextName": _WORLD,
            },
        )
        self.cdp.on("Runtime.bindingCalled", self._delivered)
        await self.cdp.send(
            "Page.addScriptToEvaluateOnNewDocument",
            {
                "source": _script(_INSTALL, self.key),
                "worldName": _WORLD,
            },
        )

    def _delivered(self, event: Any) -> None:
        if (
            type(event) is dict
            and event.get("name") == self.key + "Delivery"
            and event.get("executionContextId") == self.context_id
            and event.get("payload") == "click"
        ):
            self.clicked = True

    def invalidate(self) -> None:
        self.evidence = None
        self.expires_at = 0

    async def _document(self, policy: dict[str, Any]) -> tuple[str, str, str]:
        result = await self.cdp.send("Page.getFrameTree")
        if type(result) is not dict or type(result.get("frameTree")) is not dict:
            raise VisualGuestFailure("unstable_visual_observation")
        root = result["frameTree"]
        pending = [(root, 0)]
        count = 0
        while pending:
            entry, depth = pending.pop()
            count += 1
            if count > 32 or depth > policy["max_frame_depth"] or type(entry) is not dict:
                raise VisualGuestFailure("unsupported_visual_surface")
            frame = entry.get("frame")
            if type(frame) is not dict or type(frame.get("url")) is not str:
                raise VisualGuestFailure("unstable_visual_observation")
            parsed = urlsplit(frame["url"])
            origin = (
                f"https://{parsed.hostname}"
                if parsed.scheme == "https" and parsed.port in {None, 443}
                else None
            )
            if origin not in policy["allowed_origins"]:
                raise VisualGuestFailure("visual_publication_denied")
            if depth:
                # A child renderer is not covered by the main target's script
                # and animation freeze. Do not publish its pixels under a false
                # coherent-capture claim or manufacture frame-derived targets.
                raise VisualGuestFailure("unsupported_visual_surface")
            children = entry.get("childFrames", [])
            if type(children) is not list or count + len(children) + len(pending) > 32:
                raise VisualGuestFailure("unsupported_visual_surface")
            pending.extend((child, depth + 1) for child in children)
        frame = root["frame"]
        identity = (frame.get("id"), frame.get("loaderId"), frame.get("url"))
        if any(type(value) is not str or not value or len(value) > 8192 for value in identity):
            raise VisualGuestFailure("unstable_visual_observation")
        return identity

    async def _evaluate(self, expression: str) -> Any:
        response = await self.cdp.send(
            "Runtime.evaluate",
            {
                "expression": expression,
                "contextId": self.context_id,
                "returnByValue": True,
                "awaitPromise": False,
                "userGesture": False,
            },
        )
        if type(response) is not dict or response.get("exceptionDetails") is not None:
            raise VisualGuestFailure("unstable_visual_observation")
        result = response.get("result")
        if type(result) is not dict or "value" not in result:
            raise VisualGuestFailure("unstable_visual_observation")
        value = result["value"]
        if type(value) is dict and value.get("error"):
            raise VisualGuestFailure(value["error"])
        return value

    async def collect(self, policy: dict[str, Any], *, max_dom_nodes: int) -> dict[str, Any]:
        self.invalidate()
        self.document_identity = await self._document(policy)
        result = await self.cdp.send(
            "Page.createIsolatedWorld",
            {
                "frameId": self.document_identity[0],
                "worldName": _WORLD,
                "grantUniveralAccess": False,
            },
        )
        if type(result) is not dict or type(result.get("executionContextId")) is not int:
            raise VisualGuestFailure("unstable_visual_observation")
        self.context_id = result["executionContextId"]
        # install() runs before navigation; this fallback handles an admitted
        # about:blank document only. The world is private to this guest owner.
        await self.cdp.send(
            "Runtime.evaluate",
            {
                "expression": _script(_INSTALL, self.key),
                "contextId": self.context_id,
                "returnByValue": True,
            },
        )
        refs = ["vt_" + secrets.token_hex(16) for _ in range(policy["max_targets"])]
        result = await self._evaluate(
            _script(
                _COLLECT, self.key, options={**policy, "max_dom_nodes": max_dom_nodes}, refs=refs
            )
        )
        if type(result) is not dict or type(result.get("viewport")) is not list:
            raise VisualGuestFailure("unstable_visual_observation")
        return result

    async def seal(
        self,
        policy: dict[str, Any],
        candidate: dict[str, Any],
        screenshot: bytes,
        *,
        session_id: str,
        page_id: str,
        revision: str,
        control_epoch: int,
    ) -> dict[str, Any]:
        if (
            self.document_identity != await self._document(policy)
            or await self._evaluate(_script(_CHECK, self.key)) is not True
        ):
            raise VisualGuestFailure("unstable_visual_observation")
        width, height, scale, x, y = candidate["viewport"]
        if any(
            type(v) not in {int, float} or not math.isfinite(v)
            for v in (width, height, scale, x, y)
        ):
            raise VisualGuestFailure("unstable_visual_observation")
        self.evidence = {
            "session_id": session_id,
            "page_id": page_id,
            "page_revision": revision,
            "control_epoch": control_epoch,
            "worker_instance": self.worker_instance,
            "visual_revision": "vr_" + secrets.token_hex(16),
            "screenshot_sha256": hashlib.sha256(screenshot).hexdigest(),
            "viewport_width": width,
            "viewport_height": height,
            "device_scale": scale,
            "scroll_x": x,
            "scroll_y": y,
            "targets": candidate["targets"],
            "truncation_reasons": candidate["truncation_reasons"],
            "unsupported_reasons": candidate["unsupported_reasons"],
        }
        self.expires_at = time.monotonic() + policy["evidence_lifetime_ms"] / 1000
        return self.evidence

    async def click(self, policy: dict[str, Any], request: dict[str, Any]) -> None:
        evidence = self.evidence
        if evidence is None or time.monotonic() >= self.expires_at:
            raise VisualGuestFailure("visual_evidence_expired")
        for expected, stored in (
            ("session_id", "session_id"),
            ("page_id", "page_id"),
            ("expected_revision", "page_revision"),
            ("expected_control_epoch", "control_epoch"),
            ("visual_revision", "visual_revision"),
        ):
            if request.get(expected) != evidence[stored]:
                raise VisualGuestFailure("visual_evidence_expired")
        if request["operation"] == "click_visual_point" and (
            not policy["allow_coordinate_fallback"]
            or request.get("screenshot_sha256") != evidence["screenshot_sha256"]
        ):
            raise VisualGuestFailure("visual_evidence_expired")
        if self.document_identity != await self._document(policy):
            raise VisualGuestFailure("visual_evidence_expired")
        point = await self._evaluate(_script(_ARM, self.key, request=request))
        self.clicked = False
        self.invalidate()
        for event_type in ("mousePressed", "mouseReleased"):
            await self.cdp.send(
                "Input.dispatchMouseEvent",
                {
                    "type": event_type,
                    "x": point["x"],
                    "y": point["y"],
                    "button": "left",
                    "clickCount": 1,
                },
            )
        if self.clicked:
            return
        outcome = await self._evaluate(
            _script(
                "(() => { const a=globalThis[__KEY__].arm; return {clicked:a.clicked,failure:a.failure}; })()",
                self.key,
            )
        )
        if outcome.get("failure"):
            raise VisualGuestFailure(outcome["failure"])
        if outcome.get("clicked") is not True:
            raise VisualGuestFailure("visual_target_not_actionable")

    async def disarm(self, policy: dict[str, Any]) -> None:
        if self.context_id is None:
            return
        try:
            result = await self.cdp.send(
                "Runtime.evaluate",
                {
                    "expression": _script("globalThis[__KEY__].arm=null", self.key),
                    "contextId": self.context_id,
                    "returnByValue": True,
                },
            )
            if type(result) is not dict or "exceptionDetails" in result:
                raise VisualGuestFailure("unstable_visual_observation")
        except Exception:
            # A positively acknowledged native navigation destroys the old guard.
            if not self.clicked or self.document_identity == await self._document(policy):
                raise
