"""Fictional supplier facts and meal plans, separate from purchasing policy."""

from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

POLICY = {
    "id": "campus-purchasing",
    "revision": 1,
    "approved_suppliers": ["Campus Fresh", "Pantry Partners"],
    "maximum_order_cents": 25000,
    "requires_exact_order_approval": True,
    "rules": [
        "Respect the customer's meal quantity, budget, delivery deadline, and kitchen capacity.",
        "Use verified supplier specifications for recipe and dietary compatibility; unknown is not compliant.",
        "Compare total cost and usable cooked quantity, not the cheapest case price.",
        "Do not change the menu, dietary requirements, or supplier policy to make an option pass.",
        "Explain infeasibility and request a decision when no available option meets the plan.",
        "Only submit a reviewed exact proposal; recheck facts, stock, and plan revision before purchase.",
    ],
}


# Synthetic supplier facts. Literal data, so importing the module runs nothing.
PRODUCTS = (
    {
        "sku": "POT-WHOLE-20KG",
        "name": "Russet potatoes · whole",
        "category": "potatoes",
        "form": "whole",
        "pack_count": 1,
        "grams_each": 20000,
        "case_price_cents": 2400,
        "stock": 12,
        "cooked_yield_bps": 8000,
        "prep_minutes_per_case": 45,
        "delivery_day_offset": 1,
        "delivery_minute": 480,
        "supplier": "Campus Fresh",
        "verified_dietary": ["dairy-free", "vegan"],
        "revision": 1,
        "specification_source": "supplier-spec:POT-WHOLE-20KG:r1",
    },
    {
        "sku": "POT-PEELED-10KG",
        "name": "Peeled diced potatoes",
        "category": "potatoes",
        "form": "peeled diced",
        "pack_count": 1,
        "grams_each": 10000,
        "case_price_cents": 2500,
        "stock": 15,
        "cooked_yield_bps": 9500,
        "prep_minutes_per_case": 5,
        "delivery_day_offset": 1,
        "delivery_minute": 540,
        "supplier": "Campus Fresh",
        "verified_dietary": ["dairy-free", "vegan"],
        "revision": 1,
        "specification_source": "supplier-spec:POT-PEELED-10KG:r1",
    },
    {
        "sku": "POT-FROZEN-10KG",
        "name": "Frozen diced potatoes",
        "category": "potatoes",
        "form": "frozen diced",
        "pack_count": 1,
        "grams_each": 10000,
        "case_price_cents": 1800,
        "stock": 20,
        "cooked_yield_bps": 10000,
        "prep_minutes_per_case": 3,
        "delivery_day_offset": 1,
        "delivery_minute": 1080,
        "supplier": "Campus Fresh",
        "verified_dietary": ["dairy-free", "vegan"],
        "revision": 1,
        "specification_source": "supplier-spec:POT-FROZEN-10KG:r1",
    },
    {
        "sku": "POT-MASH-10KG",
        "name": "Prepared butter mashed potatoes",
        "category": "potatoes",
        "form": "prepared mash",
        "pack_count": 1,
        "grams_each": 10000,
        "case_price_cents": 1700,
        "stock": 20,
        "cooked_yield_bps": 10000,
        "prep_minutes_per_case": 2,
        "delivery_day_offset": 1,
        "delivery_minute": 540,
        "supplier": "Campus Fresh",
        "verified_dietary": [],
        "revision": 1,
        "specification_source": "supplier-spec:POT-MASH-10KG:r1",
    },
    {
        "sku": "POT-BABY-10KG",
        "name": "Baby roasting potatoes",
        "category": "potatoes",
        "form": "whole",
        "pack_count": 1,
        "grams_each": 10000,
        "case_price_cents": 2900,
        "stock": 0,
        "cooked_yield_bps": 9000,
        "prep_minutes_per_case": 30,
        "delivery_day_offset": 1,
        "delivery_minute": 480,
        "supplier": "Campus Fresh",
        "verified_dietary": ["dairy-free", "vegan"],
        "revision": 1,
        "specification_source": "supplier-spec:POT-BABY-10KG:r1",
    },
    {
        "sku": "RICE-WHITE-20KG",
        "name": "Long-grain white rice",
        "category": "rice",
        "form": "dry",
        "pack_count": 1,
        "grams_each": 20000,
        "case_price_cents": 3600,
        "stock": 10,
        "cooked_yield_bps": 30000,
        "prep_minutes_per_case": 30,
        "delivery_day_offset": 1,
        "delivery_minute": 480,
        "supplier": "Pantry Partners",
        "verified_dietary": ["dairy-free", "vegan"],
        "revision": 1,
        "specification_source": "supplier-spec:RICE-WHITE-20KG:r1",
    },
    {
        "sku": "RICE-READY-12KG",
        "name": "Cooked long-grain rice",
        "category": "rice",
        "form": "ready cooked",
        "pack_count": 1,
        "grams_each": 12000,
        "case_price_cents": 5500,
        "stock": 10,
        "cooked_yield_bps": 10000,
        "prep_minutes_per_case": 2,
        "delivery_day_offset": 1,
        "delivery_minute": 540,
        "supplier": "Pantry Partners",
        "verified_dietary": ["dairy-free", "vegan"],
        "revision": 1,
        "specification_source": "supplier-spec:RICE-READY-12KG:r1",
    },
    {
        "sku": "VEG-CARROT-10KG",
        "name": "Whole carrots",
        "category": "carrots",
        "form": "whole",
        "pack_count": 1,
        "grams_each": 10000,
        "case_price_cents": 1400,
        "stock": 20,
        "cooked_yield_bps": 8000,
        "prep_minutes_per_case": 40,
        "delivery_day_offset": 1,
        "delivery_minute": 480,
        "supplier": "Pantry Partners",
        "verified_dietary": ["dairy-free", "vegan"],
        "revision": 1,
        "specification_source": "supplier-spec:VEG-CARROT-10KG:r1",
    },
    {
        "sku": "VEG-CARROT-DICED-10KG",
        "name": "Peeled diced carrots",
        "category": "carrots",
        "form": "peeled diced",
        "pack_count": 1,
        "grams_each": 10000,
        "case_price_cents": 2100,
        "stock": 20,
        "cooked_yield_bps": 9500,
        "prep_minutes_per_case": 5,
        "delivery_day_offset": 1,
        "delivery_minute": 540,
        "supplier": "Pantry Partners",
        "verified_dietary": ["dairy-free", "vegan"],
        "revision": 1,
        "specification_source": "supplier-spec:VEG-CARROT-DICED-10KG:r1",
    },
)

MEALS = {
    "dinner": {
        "name": "Tomorrow's dinner · potato side",
        "category": "potatoes",
        "portions": 400,
        "cooked_grams_per_portion": 200,
        "available_cooked_grams": 20000,
        "allowed_forms": ["whole", "peeled diced", "frozen diced"],
        "budget_cents": 18000,
    },
    "rice-lunch": {
        "name": "Tomorrow's lunch · rice side",
        "category": "rice",
        "portions": 300,
        "cooked_grams_per_portion": 150,
        "available_cooked_grams": 10000,
        "allowed_forms": ["dry", "ready cooked"],
        "budget_cents": 18000,
    },
    "vegetable-side": {
        "name": "Tomorrow's dinner · carrot side",
        "category": "carrots",
        "portions": 300,
        "cooked_grams_per_portion": 100,
        "available_cooked_grams": 5000,
        "allowed_forms": ["whole", "peeled diced"],
        "budget_cents": 12000,
    },
}
STAFFING = {"short-staffed": 45, "full-team": 240}


def default_plan(meal_id, service_date):
    if meal_id not in MEALS:
        raise ValueError("Unknown meal; choose dinner, rice-lunch, or vegetable-side")
    return {
        "meal_id": meal_id,
        "revision": 1,
        **MEALS[meal_id],
        "service_date": service_date,
        "delivery_deadline_minute": 900,
        "staffing": "short-staffed",
        "prep_minutes_available": STAFFING["short-staffed"],
        "required_dietary": ["dairy-free"],
        "source": f"dining-plan:{meal_id}:r1",
    }


def tomorrow():
    return (datetime.now(ZoneInfo("America/Los_Angeles")).date() + timedelta(days=1)).isoformat()
